/*
 * Lua AST -> idiomatic V-Slice HScript (class members) for Psych Engine scripts.
 *
 * The output reads like a hand-written V-Slice script (compare with the official scripts under Funkin.assets):
 *  - Psych API calls are lowered to PlayState / FunkinSprite / FlxTween calls (see psych-api.js),
 *  - Psych globals (curBeat, songName, downscroll...) are replaced inline by the V-Slice expression holding the same data,
 *  - Lua tables become Arrays or anonymous objects, decided at translation time from how each variable is used,
 *    so no runtime type inspection is needed (the game's script sandbox blocks Type.typeof / Type.getClass),
 *  - only a handful of tiny helpers are added, and only the ones the script actually needs.
 *
 * Semantics that remain approximate (reported to the user): Lua string patterns (plain-text find/replace only),
 * tables used both as array and as record, multiple return values, goto.
 */
(function (root) {
  const C = (root.FNFConv = root.FNFConv || {});
  const A = () => C.psychApi;

  const HX_RESERVED = new Set(['var', 'function', 'class', 'new', 'this', 'null', 'true', 'false', 'if', 'else', 'for', 'while', 'do', 'switch', 'case', 'default', 'break', 'continue', 'return', 'import', 'package', 'in', 'is', 'cast', 'try', 'catch', 'throw', 'untyped', 'static', 'public', 'private', 'override', 'final', 'inline', 'extends', 'implements', 'enum', 'typedef', 'interface', 'abstract', 'using', 'macro', 'extern', 'dynamic', 'super', 'trace', 'event', 'Std', 'Math', 'Reflect', 'Type', 'String', 'Array', 'StringTools', 'FlxG', 'FlxTween', 'FlxEase', 'FlxTimer', 'FlxColor', 'FlxSprite', 'FlxText', 'PlayState', 'Conductor', 'Paths', 'Date', 'Int', 'Float', 'Bool', 'Void', 'Dynamic', 'Map']);
  /** Names of members already present on Module / NoteKind / SongEvent (or generated by us). */
  const MEMBER_RESERVED = new Set(['active', 'moduleId', 'priority', 'state', 'toString', 'id', 'noteKind', 'description', 'params', 'scoreable', 'suffix', 'noanim', 'noteStyleId', 'handleEvent', 'getEventSchema', 'processOldEvents', 'add', 'remove', 'insert']);

  /** Psych callbacks mapped to V-Slice events (see script-gen.js). */
  const KNOWN_CALLBACKS = new Set([
    'onCreate', 'onCreatePost', 'onUpdate', 'onUpdatePost', 'onBeatHit', 'onStepHit', 'onSectionHit', 'onSongStart', 'onEndSong',
    'onStartCountdown', 'onCountdownStarted', 'onCountdownTick', 'goodNoteHit', 'opponentNoteHit', 'noteMiss', 'noteMissPress',
    'onEvent', 'onGameOver', 'onPause', 'onResume', 'onSpawnNote', 'onTimerCompleted', 'onTweenCompleted', 'onDestroy',
  ]);
  /** Psych callbacks that exist but have no V-Slice equivalent here. */
  const UNSUPPORTED_CALLBACKS = new Set([
    'onKeyPress', 'onKeyRelease', 'onKeyPressPre', 'onKeyReleasePre', 'onGhostTap', 'onUpdateScore', 'preUpdateScore',
    'onRecalculateRating', 'onNextDialogue', 'onSkipDialogue', 'onEventPushed', 'eventEarlyTrigger', 'goodNoteHitPre',
    'opponentNoteHitPre', 'onMoveCamera', 'onSoundFinished', 'onCustomSubstateCreate', 'onCustomSubstateUpdate', 'onCustomSubstateDestroy',
  ]);
  const cbName = (n) => 'lua' + n[0].toUpperCase() + n.slice(1);

  const LIB_NAMES = new Set(['math', 'string', 'table', 'os', 'io', 'debug', 'coroutine', 'package']);
  const NONNEG_GLOBALS = new Set(['curBeat', 'curStep', 'curSection', 'curDecBeat', 'curDecStep', 'screenWidth', 'screenHeight', 'combo', 'misses', 'hits']);

  function hsString(s) {
    let out = '"';
    for (const ch of String(s)) {
      const c = ch.codePointAt(0);
      if (ch === '\\') out += '\\\\';
      else if (ch === '"') out += '\\"';
      else if (ch === '\n') out += '\\n';
      else if (ch === '\r') out += '\\r';
      else if (ch === '\t') out += '\\t';
      else if (c < 32) out += '\\x' + c.toString(16).padStart(2, '0');
      else out += ch;
    }
    return out + '"';
  }
  function hsNumber(v) {
    if (Number.isInteger(v) && Math.abs(v) < 2147483648) return String(v);
    if (!Number.isFinite(v)) return v > 0 ? 'Math.POSITIVE_INFINITY' : 'Math.NEGATIVE_INFINITY';
    const s = String(v);
    return /[.eE]/.test(s) ? s : s + '.0';
  }

  /** True when `s` is exactly one parenthesised group, e.g. "(a + b)". */
  function grouped(s) {
    if (s[0] !== '(' || s[s.length - 1] !== ')') return false;
    let depth = 0;
    let q = null;
    for (let i = 0; i < s.length; i++) {
      const ch = s[i];
      if (q) {
        if (ch === '\\') i++;
        else if (ch === q) q = null;
      } else if (ch === '"' || ch === "'") q = ch;
      else if (ch === '(') depth++;
      else if (ch === ')') {
        depth--;
        if (depth === 0 && i < s.length - 1) return false;
      }
    }
    return depth === 0;
  }
  const noOuter = (s) => (grouped(s) ? s.slice(1, -1) : s);
  const group = (s) => (grouped(s) ? s : '(' + s + ')');

  const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
  const isCmp = (op) => ['==', '~=', '<', '>', '<=', '>='].includes(op);
  const IND = '    ';

  class Translator {
    constructor(ast, opts) {
      this.ast = ast;
      this.opts = opts || {};
      this.helpers = new Set();
      this.fields = new Map(); // member name -> initial value (string) | null
      this.unsupported = new Map();
      this.warnings = [];
      this.callbacks = new Map();
      this.chunkFns = new Map();
      this.chunkVars = new Set();
      this.assigned = new Set();
      this.evidence = new Map(); // variable name -> {obj, arr}
      this.tags = new Map(); // literal tag -> 'sprite' | 'text'
      this.tagFields = new Map(); // literal tag -> member name
      this.fieldNames = new Set();
      this.flags = { cancelTween: false, cancelTimer: false };
      this.scopes = [];
      this.tmp = 0;
      this.skipped = 0;
      this.top = null;
      this.staticTags = this.opts.staticTags || new Set();
    }

    warn(msg) { this.warnings.push(msg); }
    unsup(name) { this.unsupported.set(name, (this.unsupported.get(name) || 0) + 1); }
    helper(n) { this.helpers.add(n); }
    uid(p) { return '__' + p + (++this.tmp); }

    /* ---------------- analysis ---------------- */
    analyze() {
      for (const st of this.ast.body) {
        if (st.t === 'Function' && st.path.length === 1) this.chunkFns.set(st.path[0], st.fn.params);
        if (st.t === 'Local') st.names.forEach((n) => this.chunkVars.add(n));
      }
      const ev = (name) => {
        if (!this.evidence.has(name)) this.evidence.set(name, { obj: false, arr: false });
        return this.evidence.get(name);
      };
      const nameOf = (n) => (n && n.t === 'Name' ? n.name : null);
      const walk = (n) => {
        if (!n || typeof n !== 'object') return;
        if (Array.isArray(n)) { n.forEach(walk); return; }
        switch (n.t) {
          case 'Assign':
            for (const tg of n.targets) if (tg.t === 'Name') this.assigned.add(tg.name);
            n.targets.forEach((tg, i) => this.noteTableCtor(nameOf(tg), n.exprs[i], ev));
            break;
          case 'Local':
            n.names.forEach((nm, i) => this.noteTableCtor(nm, n.exprs[i], ev));
            break;
          case 'Index': {
            const b = nameOf(n.obj);
            if (b && !LIB_NAMES.has(b)) {
              if (n.key.t === 'Str') ev(b).obj = true;
              else ev(b).arr = true;
            }
            break;
          }
          case 'Un':
            if (n.op === '#' && nameOf(n.e)) ev(n.e.name).arr = true;
            break;
          case 'Call': {
            const fn = n.fn;
            if (fn.t === 'Name') {
              const tag = n.args[0] && n.args[0].t === 'Str' ? n.args[0].v : null;
              if (tag != null && !this.staticTags.has(tag)) {
                if (fn.name === 'makeLuaSprite' || fn.name === 'makeAnimatedLuaSprite') this.tags.set(tag, 'sprite');
                else if (fn.name === 'makeLuaText') this.tags.set(tag, 'text');
              }
              if (fn.name === 'cancelTween') this.flags.cancelTween = true;
              if (fn.name === 'cancelTimer') this.flags.cancelTimer = true;
              if (fn.name === 'ipairs' && nameOf(n.args[0])) ev(n.args[0].name).arr = true;
            } else if (fn.t === 'Index' && fn.obj.t === 'Name' && fn.obj.name === 'table' && nameOf(n.args[0])) {
              ev(n.args[0].name).arr = true;
            }
            break;
          }
          default: break;
        }
        for (const k of Object.keys(n)) walk(n[k]);
      };
      walk(this.ast.body);
    }

    noteTableCtor(name, e, ev) {
      if (!name || !e || e.t !== 'Table' || !e.items.length) return;
      if (e.items.every((i) => i.kind === 'pos')) ev(name).arr = true;
      else ev(name).obj = true;
    }

    /** 'obj' or 'arr' for a variable name, from how the script uses it. */
    kindOfName(name) {
      const e = this.evidence.get(name);
      return e && e.obj ? 'obj' : 'arr';
    }
    kindOf(node) {
      if (node.t === 'Name') return this.kindOfName(node.name);
      if (node.t === 'Paren') return this.kindOf(node.e);
      return 'arr';
    }

    /* ---------------- names ---------------- */
    safeLocal(n) { return HX_RESERVED.has(n) ? n + '_' : n; }
    declare(n) {
      const hs = this.safeLocal(n);
      this.scopes[this.scopes.length - 1].set(n, hs);
      return hs;
    }
    lookupLocal(n) {
      for (let i = this.scopes.length - 1; i >= 0; i--) if (this.scopes[i].has(n)) return this.scopes[i].get(n);
      return null;
    }
    /** Member name for a script-level function/variable. */
    scriptName(n) {
      if (KNOWN_CALLBACKS.has(n) && this.chunkFns.has(n)) return cbName(n);
      if (HX_RESERVED.has(n) || MEMBER_RESERVED.has(n) || /^on[A-Z]/.test(n) || /^__/.test(n)) return n + '_';
      return n;
    }
    addField(name, init) {
      if (!this.fields.has(name)) this.fields.set(name, init == null ? null : init);
      return name;
    }
    globalField(n) {
      const name = this.scriptName(n);
      if (!this.chunkFns.has(n)) this.addField(name, null);
      return name;
    }
    tagField(kind, tag) {
      if (!this.tagFields.has(tag)) {
        let f = (kind === 'text' ? 'txt_' : 'spr_') + A().idPart(tag);
        while (this.fieldNames.has(f)) f += '_';
        this.fieldNames.add(f);
        this.tagFields.set(tag, f);
      }
      const f = this.tagFields.get(tag);
      this.addField(f, null);
      return f;
    }

    readName(n) {
      const l = this.lookupLocal(n);
      if (l) return l;
      if (this.chunkFns.has(n) || this.chunkVars.has(n) || this.assigned.has(n)) return this.globalField(n);
      const g = A().GLOBAL_EXPR[n];
      if (g !== undefined) return g;
      if (A().LOWER[n] || A().KNOWN_UNSUPPORTED.has(n)) { this.unsup(n); return 'null'; }
      return this.globalField(n);
    }
    writeName(n) {
      const l = this.lookupLocal(n);
      if (l) return l;
      return this.globalField(n);
    }

    /* ---------------- expression classification ---------------- */
    isPure(e) {
      return ['Nil', 'True', 'False', 'Num', 'Str'].includes(e.t) || e.t === 'Name' || (e.t === 'Index' && this.isPure(e.obj) && (e.key.t === 'Str' || e.key.t === 'Num' || e.key.t === 'Name'));
    }
    isBoolean(e) {
      if (e.t === 'True' || e.t === 'False') return true;
      if (e.t === 'Bin' && isCmp(e.op)) return true;
      if (e.t === 'Un' && e.op === 'not') return true;
      if (e.t === 'Bin' && (e.op === 'and' || e.op === 'or')) return this.isBoolean(e.l) && this.isBoolean(e.r);
      if (e.t === 'Paren') return this.isBoolean(e.e);
      if (e.t === 'Name' && !this.lookupLocal(e.name) && !this.assigned.has(e.name) && A().BOOL_GLOBALS.has(e.name)) return true;
      if (e.t === 'Call' && e.fn.t === 'Name' && A().BOOL_FUNCS.has(e.fn.name) && !this.chunkFns.has(e.fn.name)) return true;
      return false;
    }
    nonNegative(e) {
      if (e.t === 'Num') return e.v >= 0;
      if (e.t === 'Name') return NONNEG_GLOBALS.has(e.name) && !this.lookupLocal(e.name) && !this.assigned.has(e.name);
      if (e.t === 'Un' && e.op === '#') return true;
      if (e.t === 'Paren') return this.nonNegative(e.e);
      if (e.t === 'Bin' && (e.op === '+' || e.op === '*')) return this.nonNegative(e.l) && this.nonNegative(e.r);
      if (e.t === 'Call' && e.fn.t === 'Index' && e.fn.obj.t === 'Name' && e.fn.obj.name === 'math' && e.fn.key.t === 'Str' && ['floor', 'ceil', 'abs'].includes(e.fn.key.v)) return e.fn.key.v === 'abs' || (e.args[0] && this.nonNegative(e.args[0]));
      return false;
    }

    cond(e) {
      switch (e.t) {
        case 'True': return 'true';
        case 'False': case 'Nil': return 'false';
        case 'Paren': return group(this.cond(e.e));
        case 'Un':
          if (e.op === 'not') return '!' + this.wrap(this.cond(e.e), e.e);
          break;
        case 'Bin':
          if (e.op === 'and') return '(' + this.cond(e.l) + ' && ' + this.cond(e.r) + ')';
          if (e.op === 'or') return '(' + this.cond(e.l) + ' || ' + this.cond(e.r) + ')';
          if (isCmp(e.op)) return this.expr(e);
          break;
        default: break;
      }
      if (this.isBoolean(e)) return this.expr(e);
      const c = this.expr(e);
      if (e.t === 'Name' || (e.t === 'Index' && this.isPure(e))) return '(' + c + ' != null && ' + c + ' != false)';
      this.helper('__t');
      return '__t(' + c + ')';
    }
    wrap(s, e) { return e.t === 'Bin' || e.t === 'Paren' ? (s.startsWith('(') ? s : '(' + s + ')') : s; }

    args(list) { return list.map((a) => this.expr(a)); }

    expr(e) {
      switch (e.t) {
        case 'Nil': return 'null';
        case 'True': return 'true';
        case 'False': return 'false';
        case 'Num': return hsNumber(e.v);
        case 'Str': return hsString(e.v);
        case 'Vararg': this.warn('line ' + (e.line || '?') + ': varargs (...) are not supported, using an empty list'); return '[]';
        case 'Paren': return group(this.expr(e.e));
        case 'Name': return this.readName(e.name);
        case 'Func': return this.anonFunction(e.fn);
        case 'Table': return this.table(e, 'arr');
        case 'Un': {
          if (e.op === 'not') return '!' + this.wrap(this.cond(e.e), e.e);
          if (e.op === '#') return this.kindOf(e.e) === 'obj' ? 'Reflect.fields(' + this.expr(e.e) + ').length' : this.wrapObj(e.e) + '.length';
          if (e.op === '-') return '-' + this.wrap(this.expr(e.e), e.e);
          return '~' + this.wrap(this.expr(e.e), e.e);
        }
        case 'Bin': return this.binary(e);
        case 'Index': return this.indexRead(e);
        case 'Call': return this.call(e, 'expr');
        case 'Method': return this.methodCall(e);
        default: throw new Error('Unhandled expression ' + e.t);
      }
    }

    binary(e) {
      const op = e.op;
      if (op === 'and' || op === 'or') {
        if (op === 'or' && e.l.t === 'Bin' && e.l.op === 'and') return '(' + this.cond(e.l.l) + ' ? ' + this.expr(e.l.r) + ' : ' + this.expr(e.r) + ')';
        if (this.isBoolean(e.l) && this.isBoolean(e.r)) return '(' + this.cond(e.l) + (op === 'and' ? ' && ' : ' || ') + this.cond(e.r) + ')';
        if (this.isPure(e.l) && e.l.t !== 'Num' && e.l.t !== 'Str') {
          const a = this.expr(e.l);
          const test = '(' + a + ' != null && ' + a + ' != false)';
          return op === 'or' ? '(' + test + ' ? ' + a + ' : ' + this.expr(e.r) + ')' : '(' + test + ' ? ' + this.expr(e.r) + ' : ' + a + ')';
        }
        if (this.isPure(e.r)) { this.helper(op === 'or' ? '__or' : '__and'); return (op === 'or' ? '__or(' : '__and(') + this.expr(e.l) + ', ' + this.expr(e.r) + ')'; }
        this.helper(op === 'or' ? '__orf' : '__andf');
        return (op === 'or' ? '__orf(' : '__andf(') + this.expr(e.l) + ', function() { return ' + this.expr(e.r) + '; })';
      }
      if (op === '..') {
        const parts = [];
        const collect = (x) => (x.t === 'Bin' && x.op === '..' ? (collect(x.l), collect(x.r)) : parts.push(x));
        collect(e);
        const out = parts.map((p) => (p.t === 'Str' ? hsString(p.v) : p.t === 'Num' ? hsString(String(p.v)) : this.strOf(p)));
        return '(' + out.join(' + ') + ')';
      }
      const l = this.wrap(this.expr(e.l), e.l);
      const r = this.wrap(this.expr(e.r), e.r);
      switch (op) {
        case '~=': return '(' + l + ' != ' + r + ')';
        case '==': return '(' + l + ' == ' + r + ')';
        case '^': return 'Math.pow(' + this.expr(e.l) + ', ' + this.expr(e.r) + ')';
        case '//': return 'Math.floor(' + l + ' / ' + r + ')';
        case '~': return '(' + l + ' ^ ' + r + ')';
        case '%':
          if (this.nonNegative(e.l) && ((e.r.t === 'Num' && e.r.v > 0) || (e.r.t !== 'Num' && this.nonNegative(e.r)))) return '(' + l + ' % ' + r + ')';
          this.helper('__mod');
          return '__mod(' + this.expr(e.l) + ', ' + this.expr(e.r) + ')';
        default: return '(' + l + ' ' + op + ' ' + r + ')';
      }
    }

    strOf(node) {
      // Already-a-string expressions need no Std.string()
      if (node.t === 'Call' && node.fn.t === 'Name' && node.fn.name === 'tostring') return this.expr(node);
      if (node.t === 'Bin' && node.op === '..') return this.expr(node);
      return 'Std.string(' + this.expr(node) + ')';
    }

    wrapObj(o) {
      const s = this.expr(o);
      return o.t === 'Name' || o.t === 'Index' || o.t === 'Call' || o.t === 'Paren' || o.t === 'Method' ? s : '(' + s + ')';
    }

    /** Zero-based array index code for a Lua (1-based) index expression. */
    idx0(k) {
      if (k.t === 'Num') return String(k.v - 1);
      if (k.t === 'Bin' && k.op === '+' && k.r.t === 'Num') return k.r.v === 1 ? this.expr(k.l) : this.expr(k.l) + ' + ' + (k.r.v - 1);
      if (k.t === 'Bin' && k.op === '-' && k.r.t === 'Num') return this.expr(k.l) + ' - ' + (k.r.v + 1);
      return this.wrap(this.expr(k), k) + ' - 1';
    }

    indexRead(e) {
      if (e.obj.t === 'Name' && e.key.t === 'Str' && !this.lookupLocal(e.obj.name)) {
        if (e.obj.name === 'math' && e.key.v === 'pi') return 'Math.PI';
        if (e.obj.name === 'math' && e.key.v === 'huge') return 'Math.POSITIVE_INFINITY';
      }
      const base = this.wrapObj(e.obj);
      if (e.key.t === 'Str') return IDENT.test(e.key.v) && !HX_RESERVED.has(e.key.v) ? base + '.' + e.key.v : 'Reflect.field(' + base + ', ' + hsString(e.key.v) + ')';
      if (this.kindOf(e.obj) === 'obj') return 'Reflect.field(' + base + ', Std.string(' + this.expr(e.key) + '))';
      return base + '[' + this.idx0(e.key) + ']';
    }

    table(e, hint) {
      if (!e.items.length) return hint === 'obj' ? '{}' : '[]';
      if (e.items.every((i) => i.kind === 'pos')) return '[' + e.items.map((i) => this.expr(i.value)).join(', ') + ']';
      const named = e.items.every((i) => i.kind === 'named' || (i.kind === 'keyed' && i.key.t === 'Str' && IDENT.test(i.key.v)));
      if (named) return '{' + e.items.map((i) => (i.kind === 'named' ? i.key : i.key.v) + ': ' + this.expr(i.value)).join(', ') + '}';
      // {[1]="a", [2]="b"} -> array when the keys are 1..n
      if (e.items.every((i) => i.kind === 'keyed' && i.key.t === 'Num') && e.items.every((i, n) => i.key.v === n + 1)) return '[' + e.items.map((i) => this.expr(i.value)).join(', ') + ']';
      this.warn('line ' + (e.line || '?') + ': a table mixes positional and keyed entries; keeping only the named ones');
      const named2 = e.items.filter((i) => i.kind === 'named' || (i.kind === 'keyed' && i.key.t === 'Str' && IDENT.test(i.key.v)));
      return '{' + named2.map((i) => (i.kind === 'named' ? i.key : i.key.v) + ': ' + this.expr(i.value)).join(', ') + '}';
    }

    anonFunction(fn) {
      const lines = this.functionBody(fn, 1);
      const params = fn.params.map((p) => this.safeLocal(p)).join(', ');
      return 'function(' + params + ')\n{\n' + lines.join('\n') + '\n}';
    }

    /* ---------------- calls ---------------- */
    libKey(e) {
      if (e.t === 'Index' && e.obj.t === 'Name' && e.key.t === 'Str' && LIB_NAMES.has(e.obj.name) && !this.lookupLocal(e.obj.name) && !this.chunkVars.has(e.obj.name)) return e.obj.name + '.' + e.key.v;
      return null;
    }

    /** Builds the context object handed to the Psych API lowerers. */
    apiContext(call) {
      const self = this;
      const args = call.args;
      const numLit = (n) => (n && n.t === 'Num' ? n.v : n && n.t === 'Un' && n.op === '-' && n.e.t === 'Num' ? -n.e.v : null);
      return {
        n: args.length,
        has: (i) => i < args.length,
        node: (i) => args[i],
        s: (i) => (args[i] && args[i].t === 'Str' ? args[i].v : null),
        num: (i) => numLit(args[i]),
        c: (i, def) => (i < args.length ? self.expr(args[i]) : def !== undefined ? def : 'null'),
        all: () => args.map((x) => self.expr(x)),
        str: (i) => (i >= args.length ? '""' : args[i].t === 'Str' || (args[i].t === 'Bin' && args[i].op === '..') ? noOuter(self.expr(args[i])) : 'Std.string(' + self.expr(args[i]) + ')'),
        helper: (n) => self.helper(n),
        field: (n, init) => self.addField(n, init),
        hasCb: (n) => self.chunkFns.has(n),
        spriteField: (tag) => self.tagField('sprite', tag),
        textField: (tag) => self.tagField('text', tag),
        knownTag: (tag) => self.tags.has(tag),
        objByName(tag) {
          if (self.tags.has(tag)) return self.tagField(self.tags.get(tag), tag);
          if (A().ROOTS[tag]) return A().ROOTS[tag];
          return 'PlayState.instance.currentStage.getNamedProp(' + hsString(tag) + ')';
        },
        varField(name) { return self.addField('var_' + A().idPart(name), null); },
        tweenCb: (tagCode) => (self.chunkFns.has('onTweenCompleted') ? ', onComplete: function(twn) { luaOnTweenCompleted(' + tagCode + '); }' : ''),
        timerCb: (tagCode) => (self.chunkFns.has('onTimerCompleted') ? 'luaOnTimerCompleted(' + tagCode + ', tmr.loops, tmr.loopsLeft);' : ''),
        keepTween(tagCode, make) {
          if (!self.flags.cancelTween) return make + ';';
          self.addField('__tweens', '{}');
          return 'Reflect.setField(__tweens, ' + tagCode + ', ' + make + ');';
        },
        keepTimer(tagCode, make) {
          if (!self.flags.cancelTimer) return make + ';';
          self.addField('__timers', '{}');
          return 'Reflect.setField(__timers, ' + tagCode + ', ' + make + ');';
        },
      };
    }

    /** @returns {string|{stmts:string[]}|null} expression code, statement list (stmt mode) or null when not lowerable */
    lowerPsych(name, call, mode) {
      const a = this.apiContext(call);
      if (name === 'cancelTween') this.addField('__tweens', '{}');
      if (name === 'cancelTimer') this.addField('__timers', '{}');
      const r = A().lower(name, a);
      if (!r) return null;
      if (r.e !== undefined) return r.e;
      if (mode === 'stmt') return { stmts: r.s };
      return r.s.length ? '(function()\n{\n' + r.s.map((x) => IND + x.replace(/\n/g, '\n' + IND)).join('\n') + '\n})()' : 'null';
    }

    call(e, mode) {
      const fn = e.fn;
      const lk = this.libKey(fn);
      if (lk) return this.libCall(lk, e);
      if (fn.t === 'Name') {
        const name = fn.name;
        const local = this.lookupLocal(name);
        if (local) return local + '(' + this.args(e.args).join(', ') + ')';
        if (this.chunkFns.has(name) || this.chunkVars.has(name) || this.assigned.has(name)) return this.scriptName(name) + '(' + this.args(e.args).join(', ') + ')';
        const std = this.stdCall(name, e);
        if (std !== null) return std;
        if (A().LOWER[name]) {
          const r = this.lowerPsych(name, e, mode);
          if (r !== null) return r;
        }
        this.unsup(name);
        this.helper('__unsupported');
        return '__unsupported(' + hsString(name) + ')';
      }
      return this.wrapObj(fn) + '(' + this.args(e.args).join(', ') + ')';
    }

    stdCall(name, e) {
      const a = this.args(e.args);
      switch (name) {
        case 'print': return 'trace(' + a.join(', ') + ')';
        case 'tostring': return 'Std.string(' + (a[0] || 'null') + ')';
        case 'tonumber': this.helper('__num'); return '__num(' + (a[0] || 'null') + ')';
        case 'pcall': this.helper('__pcall'); return '__pcall(' + (a[0] || 'null') + ')';
        case 'type': case 'select': case 'unpack': case 'assert': case 'error': case 'setmetatable': case 'getmetatable': case 'rawget': case 'rawset': case 'next': case 'require': case 'loadstring': case 'dofile':
          this.unsup(name);
          this.helper('__unsupported');
          return '__unsupported(' + hsString(name) + ')';
        default: return null;
      }
    }

    libCall(key, e) {
      const a = this.args(e.args);
      const n = e.args;
      switch (key) {
        case 'math.floor': return 'Math.floor(' + a[0] + ')';
        case 'math.ceil': return 'Math.ceil(' + a[0] + ')';
        case 'math.abs': return 'Math.abs(' + a[0] + ')';
        case 'math.sqrt': return 'Math.sqrt(' + a[0] + ')';
        case 'math.sin': return 'Math.sin(' + a[0] + ')';
        case 'math.cos': return 'Math.cos(' + a[0] + ')';
        case 'math.tan': return 'Math.tan(' + a[0] + ')';
        case 'math.asin': return 'Math.asin(' + a[0] + ')';
        case 'math.acos': return 'Math.acos(' + a[0] + ')';
        case 'math.atan': return 'Math.atan(' + a[0] + ')';
        case 'math.atan2': return 'Math.atan2(' + a[0] + ', ' + a[1] + ')';
        case 'math.exp': return 'Math.exp(' + a[0] + ')';
        case 'math.log': return 'Math.log(' + a[0] + ')';
        case 'math.pow': return 'Math.pow(' + a[0] + ', ' + a[1] + ')';
        case 'math.max': return a.length <= 1 ? a[0] : a.slice(1).reduce((acc, x) => 'Math.max(' + acc + ', ' + x + ')', a[0]);
        case 'math.min': return a.length <= 1 ? a[0] : a.slice(1).reduce((acc, x) => 'Math.min(' + acc + ', ' + x + ')', a[0]);
        case 'math.random':
          if (!a.length) return 'FlxG.random.float()';
          if (a.length === 1) return 'FlxG.random.int(1, ' + a[0] + ')';
          return 'FlxG.random.int(' + a[0] + ', ' + a[1] + ')';
        case 'math.randomseed': return 'null';
        case 'math.rad': return '(' + a[0] + ' * Math.PI / 180)';
        case 'math.deg': return '(' + a[0] + ' * 180 / Math.PI)';
        case 'math.fmod': return '(' + a[0] + ' % ' + a[1] + ')';
        case 'string.len': return this.wrapObj(n[0]) + '.length';
        case 'string.upper': return this.wrapObj(n[0]) + '.toUpperCase()';
        case 'string.lower': return this.wrapObj(n[0]) + '.toLowerCase()';
        case 'string.sub': return this.subCode(n, a);
        case 'string.rep': this.helper('__rep'); return '__rep(' + a[0] + ', ' + a[1] + ')';
        case 'string.format': this.helper('__format'); return '__format(' + a[0] + ', [' + a.slice(1).join(', ') + '])';
        case 'string.find': this.helper('__find'); return '__find(' + a[0] + ', ' + a[1] + (a[2] ? ', ' + a[2] : '') + ')';
        case 'string.match': this.helper('__match'); return '__match(' + a[0] + ', ' + a[1] + ')';
        case 'string.gsub': return 'StringTools.replace(' + a[0] + ', ' + a[1] + ', ' + a[2] + ')';
        case 'table.insert':
          return n.length >= 3 ? this.wrapObj(n[0]) + '.insert(' + this.idx0(n[1]) + ', ' + a[2] + ')' : this.wrapObj(n[0]) + '.push(' + a[1] + ')';
        case 'table.remove':
          return n.length >= 2 ? this.wrapObj(n[0]) + '.splice(' + this.idx0(n[1]) + ', 1)[0]' : this.wrapObj(n[0]) + '.pop()';
        case 'table.concat': return this.wrapObj(n[0]) + '.join(' + (a[1] || '""') + ')';
        case 'table.sort': {
          const t = this.wrapObj(n[0]);
          if (n.length < 2) return t + '.sort(function(a, b)\n{\n' + IND + 'return a < b ? -1 : (a > b ? 1 : 0);\n})';
          return t + '.sort(function(a, b)\n{\n' + IND + 'var cmp = ' + a[1].replace(/\n/g, '\n' + IND) + ';\n' + IND + 'return cmp(a, b) ? -1 : (cmp(b, a) ? 1 : 0);\n})';
        }
        case 'os.time': return 'Std.int(Date.now().getTime() / 1000)';
        case 'os.clock': return '(FlxG.game.ticks / 1000)';
        default:
          this.unsup(key);
          this.helper('__unsupported');
          return '__unsupported(' + hsString(key) + ')';
      }
    }

    subCode(n, a) {
      const lit = (i) => (n[i] && n[i].t === 'Num' && n[i].v >= 1 ? n[i].v : null);
      const s = this.wrapObj(n[0]);
      if (lit(1) != null && n.length === 2) return s + '.substr(' + (lit(1) - 1) + ')';
      if (lit(1) != null && lit(2) != null) return s + '.substr(' + (lit(1) - 1) + ', ' + (lit(2) - lit(1) + 1) + ')';
      this.helper('__sub');
      return '__sub(' + a.join(', ') + ')';
    }

    methodCall(e) {
      const base = this.wrapObj(e.obj);
      const a = this.args(e.args);
      switch (e.name) {
        case 'upper': return base + '.toUpperCase()';
        case 'lower': return base + '.toLowerCase()';
        case 'len': return base + '.length';
        case 'sub': return this.subCode([e.obj, ...e.args], [this.expr(e.obj), ...a]);
        case 'rep': this.helper('__rep'); return '__rep(' + base + ', ' + a[0] + ')';
        case 'format': this.helper('__format'); return '__format(' + base + ', [' + a.join(', ') + '])';
        case 'find': this.helper('__find'); return '__find(' + base + ', ' + a.join(', ') + ')';
        case 'match': this.helper('__match'); return '__match(' + base + ', ' + a.join(', ') + ')';
        case 'gsub': return 'StringTools.replace(' + base + ', ' + a[0] + ', ' + a[1] + ')';
        default: return base + '.' + e.name + '(' + a.join(', ') + ')';
      }
    }

    /* ---------------- statements ---------------- */
    pad(depth) { return IND.repeat(depth); }
    push(out, depth, text) {
      for (const line of String(text).split('\n')) out.push(this.pad(depth) + line);
    }

    block(body, depth) {
      const out = [];
      for (const st of body) this.stmt(st, depth, out);
      return out;
    }
    withScope(fn) {
      this.scopes.push(new Map());
      const r = fn();
      this.scopes.pop();
      return r;
    }
    functionBody(fn, depth) {
      return this.withScope(() => {
        fn.params.forEach((p) => this.declare(p));
        return this.block(fn.body, depth);
      });
    }

    shouldSkip(st) {
      const skip = this.opts.skipCall;
      if (!skip || st.t !== 'CallStat' || st.expr.t !== 'Call' || st.expr.fn.t !== 'Name') return false;
      const first = st.expr.args[0];
      return skip(st.expr.fn.name, first && first.t === 'Str' ? first.v : null, this.top);
    }

    stmt(st, depth, out) {
      switch (st.t) {
        case 'Local': {
          const chunk = this.scopes.length === 0;
          const vals = st.exprs.map((x, i) => this.valueFor(st.names[i], x));
          st.names.forEach((n, i) => {
            const v = vals[i] !== undefined ? vals[i] : 'null';
            if (chunk) this.push(out, depth, this.globalField(n) + ' = ' + noOuter(v) + ';');
            else {
              const hs = this.declare(n);
              this.push(out, depth, 'var ' + hs + ' = ' + noOuter(v) + ';');
            }
          });
          break;
        }
        case 'Assign': {
          if (st.targets.length === 1 && st.exprs.length >= 1) {
            this.push(out, depth, this.assignTo(st.targets[0], this.valueFor(st.targets[0].t === 'Name' ? st.targets[0].name : null, st.exprs[0])) + ';');
            break;
          }
          const tmps = st.exprs.map((x) => {
            const t = this.uid('t');
            this.push(out, depth, 'var ' + t + ' = ' + this.expr(x) + ';');
            return t;
          });
          st.targets.forEach((tg, i) => this.push(out, depth, this.assignTo(tg, tmps[i] !== undefined ? tmps[i] : 'null') + ';'));
          break;
        }
        case 'CallStat': {
          if (this.shouldSkip(st)) { this.skipped++; break; }
          const e = st.expr;
          if (e.t === 'Call' && e.fn.t === 'Name' && !this.lookupLocal(e.fn.name) && !this.chunkFns.has(e.fn.name) && !this.chunkVars.has(e.fn.name) && A().LOWER[e.fn.name]) {
            const r = this.lowerPsych(e.fn.name, e, 'stmt');
            if (r !== null && typeof r === 'object') { r.stmts.forEach((s) => this.push(out, depth, s)); break; }
            if (r !== null) { this.push(out, depth, r + ';'); break; }
          }
          const code = this.expr(e);
          if (code !== 'null') this.push(out, depth, code + ';');
          break;
        }
        case 'Do':
          this.push(out, depth, '{');
          this.withScope(() => out.push(...this.block(st.body, depth + 1)));
          this.push(out, depth, '}');
          break;
        case 'While':
          this.push(out, depth, 'while (' + noOuter(this.cond(st.cond)) + ')');
          this.push(out, depth, '{');
          this.withScope(() => out.push(...this.block(st.body, depth + 1)));
          this.push(out, depth, '}');
          break;
        case 'Repeat':
          this.push(out, depth, 'while (true)');
          this.push(out, depth, '{');
          this.withScope(() => {
            out.push(...this.block(st.body, depth + 1));
            this.push(out, depth + 1, 'if (' + noOuter(this.cond(st.cond)) + ') break;');
          });
          this.push(out, depth, '}');
          break;
        case 'If': {
          st.clauses.forEach((c, i) => {
            this.push(out, depth, (i === 0 ? 'if (' : 'else if (') + noOuter(this.cond(c.cond)) + ')');
            this.push(out, depth, '{');
            this.withScope(() => out.push(...this.block(c.body, depth + 1)));
            this.push(out, depth, '}');
          });
          if (st.orelse) {
            this.push(out, depth, 'else');
            this.push(out, depth, '{');
            this.withScope(() => out.push(...this.block(st.orelse, depth + 1)));
            this.push(out, depth, '}');
          }
          break;
        }
        case 'NumFor': this.numFor(st, depth, out); break;
        case 'GenFor': this.genFor(st, depth, out); break;
        case 'Function': this.functionStmt(st, depth, out); break;
        case 'Return': {
          if (!st.exprs.length) this.push(out, depth, 'return;');
          else {
            if (st.exprs.length > 1) this.warn('line ' + st.line + ': multiple return values are not supported; returning the first');
            this.push(out, depth, 'return ' + noOuter(this.expr(st.exprs[0])) + ';');
          }
          break;
        }
        case 'Break': this.push(out, depth, 'break;'); break;
        case 'Goto': case 'Label': this.warn('line ' + st.line + ': goto/labels are not supported'); break;
        default: throw new Error('Unhandled statement ' + st.t);
      }
    }

    /** Value code for an assignment to variable `name` (empty tables become {} or [] by how the variable is used). */
    valueFor(name, e) {
      if (!e) return undefined;
      if (e.t === 'Table') return this.table(e, name && this.kindOfName(name) === 'obj' ? 'obj' : 'arr');
      return this.expr(e);
    }

    numFor(st, depth, out) {
      const intLit = (n) => n && n.t === 'Num' && Number.isInteger(n.v);
      const stepOk = !st.step || (intLit(st.step) && st.step.v === 1);
      this.withScope(() => {
        const hs = this.declare(st.name);
        if (stepOk) {
          const start = intLit(st.start) ? String(st.start.v) : 'Std.int(' + this.expr(st.start) + ')';
          const limit = intLit(st.limit) ? String(st.limit.v + 1) : 'Std.int(' + this.expr(st.limit) + ') + 1';
          this.push(out, depth, 'for (' + hs + ' in ' + start + '...' + limit + ')');
          this.push(out, depth, '{');
          out.push(...this.block(st.body, depth + 1));
          this.push(out, depth, '}');
          return;
        }
        const i = this.uid('i');
        const lim = this.uid('lim');
        const stp = this.uid('stp');
        this.push(out, depth, '{');
        this.push(out, depth + 1, 'var ' + i + ' = ' + this.expr(st.start) + ';');
        this.push(out, depth + 1, 'var ' + lim + ' = ' + this.expr(st.limit) + ';');
        this.push(out, depth + 1, 'var ' + stp + ' = ' + this.expr(st.step) + ';');
        const stepNum = st.step.t === 'Num' ? st.step.v : st.step.t === 'Un' && st.step.op === '-' && st.step.e.t === 'Num' ? -st.step.e.v : null;
        const test = stepNum != null ? (stepNum > 0 ? i + ' <= ' + lim : i + ' >= ' + lim) : '(' + stp + ' > 0 ? ' + i + ' <= ' + lim + ' : ' + i + ' >= ' + lim + ')';
        this.push(out, depth + 1, 'while (' + test + ')');
        this.push(out, depth + 1, '{');
        this.push(out, depth + 2, 'var ' + hs + ' = ' + i + ';');
        out.push(...this.block(st.body, depth + 2));
        this.push(out, depth + 2, i + ' += ' + stp + ';');
        this.push(out, depth + 1, '}');
        this.push(out, depth, '}');
      });
    }

    genFor(st, depth, out) {
      const e0 = st.exprs[0];
      let target = null;
      let isIpairs = false;
      if (e0 && e0.t === 'Call' && e0.fn.t === 'Name' && (e0.fn.name === 'pairs' || e0.fn.name === 'ipairs') && e0.args.length === 1 && !this.lookupLocal(e0.fn.name)) {
        target = e0.args[0];
        isIpairs = e0.fn.name === 'ipairs';
      } else {
        this.warn('line ' + st.line + ': generic for-loop iterator is not pairs/ipairs; treated as pairs()');
        target = e0;
      }
      const code = this.wrapObj(target);
      const kind = isIpairs ? 'arr' : this.kindOf(target);
      this.withScope(() => {
        if (kind === 'obj') {
          const kName = st.names[0] ? this.declare(st.names[0]) : '__k';
          this.push(out, depth, 'for (' + kName + ' in Reflect.fields(' + code + '))');
          this.push(out, depth, '{');
          if (st.names[1]) this.push(out, depth + 1, 'var ' + this.declare(st.names[1]) + ' = Reflect.field(' + code + ', ' + kName + ');');
          out.push(...this.block(st.body, depth + 1));
          this.push(out, depth, '}');
        } else {
          const counter = this.uid('n');
          this.push(out, depth, '{');
          this.push(out, depth + 1, 'var ' + counter + ' = 0;');
          const vName = st.names[1] ? this.declare(st.names[1]) : '__v';
          this.push(out, depth + 1, 'for (' + vName + ' in ' + code + ')');
          this.push(out, depth + 1, '{');
          this.push(out, depth + 2, counter + '++;');
          if (st.names[0]) this.push(out, depth + 2, 'var ' + this.declare(st.names[0]) + ' = ' + counter + ';');
          out.push(...this.block(st.body, depth + 2));
          this.push(out, depth + 1, '}');
          this.push(out, depth, '}');
        }
      });
    }

    assignTo(target, valueCode) {
      valueCode = noOuter(valueCode);
      if (target.t === 'Name') return this.writeName(target.name) + ' = ' + valueCode;
      const base = this.wrapObj(target.obj);
      if (target.key.t === 'Str') return IDENT.test(target.key.v) && !HX_RESERVED.has(target.key.v) ? base + '.' + target.key.v + ' = ' + valueCode : 'Reflect.setField(' + base + ', ' + hsString(target.key.v) + ', ' + valueCode + ')';
      if (this.kindOf(target.obj) === 'obj') return 'Reflect.setField(' + base + ', Std.string(' + this.expr(target.key) + '), ' + valueCode + ')';
      return base + '[' + this.idx0(target.key) + '] = ' + valueCode;
    }

    functionStmt(st, depth, out) {
      const isChunk = this.scopes.length === 0;
      if (st.path.length === 1 && isChunk) {
        const name = st.path[0];
        const isCb = KNOWN_CALLBACKS.has(name);
        const hs = this.scriptName(name);
        if (isCb) this.callbacks.set(name, { params: st.fn.params, fn: hs });
        else if (UNSUPPORTED_CALLBACKS.has(name)) this.warn('callback "' + name + '" has no V-Slice equivalent and will never run');
        const saved = this.top;
        this.top = name;
        const params = st.fn.params.map((x) => this.safeLocal(x)).join(', ');
        const body = this.functionBody(st.fn, depth + 1);
        this.top = saved;
        this.push(out, depth, 'function ' + hs + '(' + params + ')');
        this.push(out, depth, '{');
        out.push(...body);
        this.push(out, depth, '}');
        return;
      }
      if (st.path.length === 1) {
        const hs = this.declare(st.path[0]);
        this.push(out, depth, 'var ' + hs + ' = null;');
        this.push(out, depth, hs + ' = ' + this.anonFunction(st.fn) + ';');
        return;
      }
      // function a.b.c() / a:b() -> closure stored on a table field
      let obj = { t: 'Name', name: st.path[0] };
      for (let i = 1; i < st.path.length - 1; i++) obj = { t: 'Index', obj, key: { t: 'Str', v: st.path[i] } };
      const last = { t: 'Index', obj, key: { t: 'Str', v: st.path[st.path.length - 1] } };
      this.push(out, depth, this.assignTo(last, this.anonFunction(st.fn)) + ';');
    }

    /* ---------------- top level ---------------- */
    run() {
      this.analyze();
      const fnBlocks = [];
      const mainLines = [];
      for (const st of this.ast.body) {
        if (st.t === 'Function' && st.path.length === 1) {
          const lines = [];
          this.functionStmt(st, 1, lines);
          fnBlocks.push(lines.join('\n'));
        } else {
          this.top = '__main';
          this.stmt(st, 2, mainLines);
        }
      }
      this.mainCount = mainLines.length;
      const fieldLines = [];
      for (const [name, init] of this.fields) fieldLines.push(IND + 'var ' + name + (init != null ? ' = ' + init : '') + ';');
      const main = [IND + 'function luaMain()', IND + '{', ...mainLines, IND + '}'].join('\n');
      this.fieldsText = fieldLines.join('\n');
      this.functionsText = [main, ...fnBlocks].join('\n\n');
      return (this.fieldsText ? this.fieldsText + '\n\n' : '') + this.functionsText;
    }
  }

  /**
   * @param {string} source Lua source
   * @param {{skipCall?:function(string,string,string):boolean, staticTags?:Set<string>}} opts
   */
  function translate(source, opts) {
    const ast = C.lua.parse(source);
    const t = new Translator(ast, opts);
    const members = t.run();
    return {
      members,
      fieldsText: t.fieldsText,
      functionsText: t.functionsText,
      callbacks: t.callbacks,
      helpers: t.helpers,
      unsupported: t.unsupported,
      warnings: t.warnings,
      skippedStatic: t.skipped,
      mainFn: 'luaMain',
      hasMainStatements: t.mainCount > 0,
      fields: t.fields,
    };
  }

  C.psychLua = { translate, KNOWN_CALLBACKS, UNSUPPORTED_CALLBACKS, hsString, hsNumber, cbName };
})(typeof window !== 'undefined' ? window : globalThis);
