// Each case defines `function main()` returning a number, string or boolean.
module.exports = [
  { name: 'arithmetic and precedence', lua: `function main() return 2 + 3 * 4 - 10 / 4 + 7 % 3 + 2 ^ 3 end` },
  { name: 'negative modulo (floor semantics)', lua: `function main() return (-7 % 3) * 100 + (7 % -3) * 10 + (-7 % -3) end` },
  { name: 'unary and parentheses', lua: `function main() return -(2 + 3) * -2 + (-3) ^ 2 end` },
  { name: 'string concatenation with numbers', lua: `function main() return "a" .. 1 .. "b" .. (2 + 3) .. "c" end` },
  { name: 'comparison chain', lua: `function main() local a, b = 3, 5 if a < b and b >= 5 and a ~= b and not (a == b) then return 1 else return 0 end end` },
  { name: 'numeric for ascending', lua: `function main() local s = 0 for i = 1, 10 do s = s + i end return s end` },
  { name: 'numeric for descending with step', lua: `function main() local s = "" for i = 10, 1, -3 do s = s .. i .. "," end return s end` },
  { name: 'numeric for with float step', lua: `function main() local n = 0 for x = 0, 1, 0.25 do n = n + 1 end return n end` },
  { name: 'loop variable is per-iteration (closures)', lua: `function main() local fs = {} for i = 1, 3 do fs[i] = function() return i * 10 end end return fs[1]() + fs[2]() + fs[3]() end` },
  { name: 'while with break', lua: `function main() local i, s = 0, 0 while true do i = i + 1 if i > 5 then break end s = s + i end return s end` },
  { name: 'repeat until sees body locals', lua: `function main() local n = 0 repeat local done = n >= 4 n = n + 1 until done return n end` },
  { name: 'nested loops', lua: `function main() local c = 0 for i = 1, 4 do for j = 1, i do c = c + 1 end end return c end` },
  { name: 'array length and index (1-based)', lua: `function main() local t = {10, 20, 30} return t[1] * 100 + t[3] * 10 + #t end` },
  { name: 'table.insert / remove / concat', lua: `function main() local t = {} table.insert(t, "a") table.insert(t, "b") table.insert(t, 1, "z") local r = table.remove(t) return table.concat(t, "-") .. r .. #t end` },
  { name: 'table.remove at position', lua: `function main() local t = {1, 2, 3, 4} table.remove(t, 2) return table.concat(t, ",") end` },
  { name: 'ipairs sum', lua: `function main() local s = 0 for i, v in ipairs({5, 6, 7}) do s = s + i * v end return s end` },
  { name: 'pairs over record', lua: `function main() local o = {a = 1, b = 2, c = 3} local s = 0 for k, v in pairs(o) do s = s + v end return s end` },
  { name: 'record fields and nesting', lua: `function main() local o = {pos = {x = 3, y = 4}, name = "p"} return o.pos.x * o.pos.y .. o.name end` },
  { name: 'field assignment on tables', lua: `function main() local o = {} o.count = 0 for i = 1, 3 do o.count = o.count + i end return o.count end` },
  { name: '2D arrays', lua: `function main() local g = {} for i = 1, 3 do g[i] = {} for j = 1, 3 do g[i][j] = i * j end end return g[2][3] + g[3][3] end` },
  { name: 'closures keep state', lua: `function main() local function counter() local c = 0 return function() c = c + 1 return c end end local a, b = counter(), counter() a() a() b() return a() * 10 + b() end` },
  { name: 'recursion fib', lua: `function fib(n) if n < 2 then return n end return fib(n - 1) + fib(n - 2) end function main() return fib(15) end` },
  { name: 'recursion factorial', lua: `local function fact(n) if n <= 1 then return 1 end return n * fact(n - 1) end function main() return fact(8) end` },
  { name: 'and/or default idiom', lua: `function main() local x = nil local y = false return (x or 5) + (y and 1 or 2) + (3 and 4 or 5) end` },
  { name: 'ternary idiom with false value', lua: `function main() local a = true return a and 7 or 9 end` },
  { name: 'truthiness: 0 and empty string are true', lua: `function main() local n = 0 if 0 then n = n + 1 end if "" then n = n + 10 end if nil then n = n + 100 end return n end` },
  { name: 'not operator', lua: `function main() local t = nil if not t then return 1 end return 0 end` },
  { name: 'swap assignment', lua: `function main() local a, b = 1, 2 a, b = b, a return a * 10 + b end` },
  { name: 'globals across functions', lua: `counter = 0 function inc() counter = counter + 1 end function main() inc() inc() inc() return counter end` },
  { name: 'chunk-level locals', lua: `local total = 5 local function add(n) total = total + n end function main() add(3) add(4) return total end` },
  { name: 'shadowed locals', lua: `function main() local x = 1 do local x = 2 x = x + 1 end return x end` },
  { name: 'string.sub / len / upper', lua: `function main() local s = "Hello World" return string.sub(s, 1, 5) .. string.upper("x") .. #s .. string.sub(s, -5) end` },
  { name: 'string methods via colon', lua: `function main() local s = "abc" return s:upper() .. s:len() .. s:sub(2) end` },
  { name: 'string.rep and format', lua: `function main() return string.rep("ab", 3) .. string.format("%d|%5.2f|%s", 42, 3.14159, "z") end` },
  { name: 'string.find plain', lua: `function main() return string.find("hello world", "wor", 1, true) end` },
  { name: 'math functions', lua: `function main() return math.floor(3.7) + math.ceil(3.2) + math.abs(-4) + math.max(1, 9, 3) + math.min(4, 2) + math.sqrt(16) end` },
  { name: 'math.huge and pi', lua: `function main() return (math.pi > 3.14 and math.pi < 3.15 and 1 or 0) + (math.huge > 1000000 and 10 or 0) end` },
  { name: 'tostring / tonumber', lua: `function main() return tonumber("42") + tonumber("0.5") + #tostring(12345) end` },
  { name: 'tonumber of garbage is nil', lua: `function main() local n = tonumber("abc") if n == nil then return "nil" end return "num" end` },
  { name: 'table.sort numbers', lua: `function main() local t = {5, 2, 9, 1} table.sort(t) return table.concat(t, ",") end` },
  { name: 'table.sort with comparator', lua: `function main() local t = {5, 2, 9, 1} table.sort(t, function(a, b) return a > b end) return table.concat(t, ",") end` },
  { name: 'array built in loop, reversed', lua: `function main() local r = {} for i = 1, 5 do table.insert(r, 1, i) end return table.concat(r, "") end` },
  { name: 'keyed table constructor', lua: `function main() local t = {[1] = "a", [2] = "b", [3] = "c"} return #t .. t[2] end` },
  { name: 'mixed table constructor', lua: `function main() local t = {"x", "y", n = 2} return t[1] .. t[2] .. t.n end` },
  { name: 'callback invoked through table field', lua: `function main() local ops = {add = function(a, b) return a + b end, mul = function(a, b) return a * b end} return ops.add(2, 3) * 10 + ops.mul(2, 3) end` },
  { name: 'functions as arguments', lua: `local function apply(f, v) return f(f(v)) end function main() return apply(function(x) return x * 3 end, 2) end` },
  { name: 'missing arguments are nil', lua: `local function f(a, b) if b == nil then return a end return a + b end function main() return f(5) * 10 + f(5, 1) end` },
  { name: 'integer division idiom', lua: `function main() return math.floor(7 / 2) * 10 + math.floor(-7 / 2) end` },
  { name: 'beat/step style math', lua: `function main() local curBeat = 13 local sec = math.floor(curBeat / 4) return sec * 100 + curBeat % 4 end` },
  { name: 'nested if/elseif/else', lua: `local function grade(n) if n >= 90 then return "A" elseif n >= 80 then return "B" elseif n >= 70 then return "C" else return "F" end end function main() return grade(95) .. grade(85) .. grade(75) .. grade(10) end` },
  { name: 'shadowed Lua keyword-like names', lua: `function main() local var, new, class = 1, 2, 3 return var + new * class end` },
  { name: 'string comparison', lua: `function main() if "abc" < "abd" and "b" > "a" and "x" == "x" then return 1 end return 0 end` },
  { name: 'long string and escapes', lua: `function main() local s = "tab\\there" local l = [[line1\nline2]] return #s + #l end` },
  { name: 'tables as sets', lua: `function main() local seen = {} local n = 0 for _, k in ipairs({"a", "b", "a", "c", "b"}) do if not seen[k] then seen[k] = true n = n + 1 end end return n end` },
  { name: 'queue simulation', lua: `function main() local q = {} for i = 1, 5 do table.insert(q, i * i) end local s = 0 while #q > 0 do s = s + table.remove(q, 1) end return s end` },
];
